export type ArtigoModel = {
  id?: string,
  url: string,
  titulo: string,
  subtitulo?: string,
  metatags?: string[],
  subcategoriaId: string,
  dataCriacao?: Date,
  dataEdicao?: Date,
  dataAgendamento?: Date,
  tempoLeitura: number,
  conteudoArtigo: string,
  autorId:  number,
  serieId?:  number,
}
